config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :bank_details
  end

  get '/bank_details/:id' => 'bank_details#bank_details'

end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/bank_detail.rb
class Spree::BankDetail < ActiveRecord::Base
  attr_accessible :account_name, :account_number, :bank, :bank_branch, :status
  has_many :payments, :as => :source, :class_name => 'Spree::Payment'

  validates :account_name, :account_number, :bank, :presence => true

end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do

  def bank_detail
    if self.payment_method.type == "Spree::PaymentMethod::BankTransfer"
      Spree::BankDetail.find(self.payment.source_id)
    end
  end

end

app/models/spree/payment_decorator.rb
Spree::Payment.class_eval do

  attr_accessible :source_id

end

app/models/spree/payment_method/bank_transfer.rb
module Spree
  class PaymentMethod::BankTransfer < PaymentMethod

    def actions
      %w{capture void}
    end

    def payment_source_class
      BankTransfer
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def void(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def source_required?
      #true
      false
    end

    def payment_profiles_supported?
      true
    end

  end
end

app/models/spree/payment_method/cash_on_delivery.rb
module Spree
  class PaymentMethod::CashOnDelivery < PaymentMethod

    def actions
      %w{capture void}
    end

    def payment_source_class
      BankTransfer
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def void(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def source_required?
      #true
      false
    end

  end
end

app/models/spree/shipment_decorator.rb
Spree::Shipment.class_eval do

  state_machine :initial => 'pending' do
    event :ship do
      transition :from => 'pending', :to => 'shipped', :if => :check_cod_if_true?
    end
  end

  def check_cod_if_true?
    return_value = false
    self.order.payments.each do |payment|
      if payment.payment_method.type == "Spree::PaymentMethod::CashOnDelivery" && payment.state != 'void' && self.order.shipment_state != "backorder"
        return_value = true
        break
      end
    end
    return_value
  end

end

app/controllers/spree/admin/bank_details_controller.rb
module Spree
  module Admin
    class BankDetailsController < ResourceController

      def index
        @bank_details = BankDetail.all(:conditions => {:status => "owner"})
      end

      def new
        @bank_detail = BankDetail.new
      end

      def edit
        @bank_detail = BankDetail.find(params[:id])
      end

      def create
        @bank_detail = BankDetail.new(params[:bank_detail])
        if @bank_detail.save
          flash.notice = I18n.t(:successfully_created, :resource => I18n.t(:bank_detail))
          respond_with(@bank_detail, :location => admin_bank_details_path(@bank_detail))
        else
          #invoke_callbacks(:create, :fails)
          respond_with(@bank_detail)
        end
      end

    end
  end
end

app/controllers/spree/admin/payment_controller_decorator.rb
Spree::Admin::PaymentsController.class_eval do
  after_filter :bank_detail, :only => [:create]

  def bank_detail
    if @payment.payment_method.type == "Spree::PaymentMethod::BankTransfer"
      @bank_detail = Spree::BankDetail.create(params[:bank])
      @payment.update_attributes(:source_id => @bank_detail.id)
    end
  end

end

app/controllers/spree/admin/payments_controller_decorator.rb
Spree::Admin::PaymentsController.class_eval do

  after_filter :bank_detail, :only => [:create]
  before_filter :bank_validation, :only => [:create]

  # To add bank detail for detail information of customer's bank that used for their payment
  def bank_detail
    if @order.payments.last.payment_method.type == "Spree::PaymentMethod::BankTransfer"
      @bank_detail = Spree::BankDetail.new(params[:bank])
      if @bank_detail.valid?
        @bank_detail.save
        @order.payments.last.update_attributes(:source_id => @bank_detail.id)
      end
    end
  end

  # To validate the bank's informations while making payment
  def bank_validation
    if params[:bank]
      if Spree::PaymentMethod.find(params[:payment][:payment_method_id]).type == "Spree::PaymentMethod::BankTransfer"
        @bank_detail = Spree::BankDetail.new(params[:bank])
        if @bank_detail.valid?
        else
          flash[:error] = "Bank informations was incomplete"
          redirect_to :back
          return false
        end
      end
    end
  end

end

app/controllers/spree/bank_details_controller.rb
class Spree::BankDetailsController < ApplicationController

  def bank_details
    @bank_owner = Spree::BankDetail.find_by_bank(params[:id], :conditions => {:status => "owner"})
    respond_to do |format|
      format.json {render :json => @bank_owner}
    end
  end

end

app/controllers/spree/checkout_controller_decorator.rb
Spree::CheckoutController.class_eval do

  after_filter :bank_detail, :only => [:update]
  before_filter :bank_validation, :only => [:update]

  # To add bank detail for detail information of customer's bank that used for their payment
  def bank_detail
    if current_order.payment.present? && current_order.payment.source_id.nil?
      if current_order.payment.payment_method.type == "Spree::PaymentMethod::BankTransfer"
        @bank_detail = Spree::BankDetail.new(params[:bank])
        if @bank_detail.valid?
          @bank_detail.save
          current_order.payment.update_attributes(:source_id => @bank_detail.id)
        end
      end
    end
  end

  # To validate the bank's informations while checking out the orders on the front end
  def bank_validation
    if params[:bank]
      if Spree::PaymentMethod.find(params[:order][:payments_attributes][0][:payment_method_id]).type == "Spree::PaymentMethod::BankTransfer"
        @bank_detail = Spree::BankDetail.new(params[:bank])
        if @bank_detail.valid?
        else
          flash[:error] = "Bank informations was incomplete"
          redirect_to :back
          return false
        end
      end
    end
  end

end

app/helpers/spree/bank_details_helper.rb
module Spree::BankDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spree/admin/bank_details/_form.html.erb
<div data-hook="admin_bank_detail_form_fields">
  <%= f.field_container :bank do %>
    <%= f.label :bank, t(:bank) %><br />
    <%= f.text_field :bank %>
  <% end %>

  <%= f.field_container :account_name do %>
    <%= f.label :account_name, t(:account_name) %><br />
    <%= f.text_field :account_name %>
  <% end %>

  <%= f.field_container :account_number do %>
    <%= f.label :account_number, t(:account_number) %><br />
    <%= f.text_field :account_number %>
  <% end %>

  <%= f.field_container :bank_branch do %>
    <%= f.label :bank_branch, t(:bank_branch) %><br />
    <%= f.text_field :bank_branch %>
  <% end %>

  <%= f.hidden_field :status, :value => "owner" %>
</div>

app/views/spree/admin/bank_details/edit.html.erb
<h1><%= t(:editing_bank_detail) %></h1>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @bank_detail } %>

<%= form_for [:admin, @bank_detail] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/bank_details/index.html.erb
<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
    <p><%= button_link_to t(:new_bank), new_admin_bank_detail_url, :icon => 'add', :id => 'new_admin_bank_detail_link' %></p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:listing_bank_details) %></h1>
<table class="index" id='listing_bank_details' data-hook>
  <thead>
    <tr data-hook="tax_header">
      <th><%= t(:bank) %></th>
      <th><%= t(:account_number) %></th>
      <th><%= t(:account_name) %></th>
      <th><%= t(:bank_branch) %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @bank_details.each do |bank_detail|
         @edit_url = edit_admin_bank_detail_path(bank_detail)
         @delete_url = admin_bank_detail_path(bank_detail)
    %>
      <tr id="<%= spree_dom_id bank_detail %>" data-hook="tax_row">
        <td><%= bank_detail.bank %></td>
        <td><%= bank_detail.account_number %></td>
        <td><%= bank_detail.account_name %></td>
        <td><%= bank_detail.bank_branch %></td>
        <td class="actions">
          <%= link_to_edit bank_detail, :class => 'edit' %> &nbsp;
          <%= link_to_delete bank_detail %>
      </tr>
    <% end %>
    <% if @bank_details.empty? %>
      <tr data-hook="bank_detail_none"><td colspan="4"><%= t(:none) %></td></tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/bank_details/new.html.erb
<h1><%= t(:new_bank_detail) %></h1>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @bank_detail } %>

<%= form_for [:admin, @bank_detail] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= render :partial => 'spree/admin/shared/new_resource_links' %>
<% end %>

app/views/spree/admin/payments/source_forms/_banktransfer.html.erb
<fieldset>
  <div id="account_form" data-hook>
    <%#= image_tag 'credit_cards/credit_card.gif', :id => 'credit-card-image' %>
    <% param_prefix = "payment_source[#{payment_method.id}]" %>

    <div data-hook="bank">
      <%= label_tag nil, t(:bank) %><br />
      <%#= hidden_field_tag "#{param_prefix}","" %>
      <%#= Rails.application.config.spree.payment_methods.inspect %>
      <%= select_tag("[bank][bank]", options_from_collection_for_select(Spree::BankDetail.all(:conditions => {:status => "owner"}), :bank, :bank)) %>
      <span class="required">*</span>
      <br />
      <%= label_tag nil, t(:account_name) %><br />
      <%= text_field_tag "[bank][account_name]"  %>
      <span class="required">*</span>
      <br />
      <%= label_tag nil, t(:account_number) %><br />
      <%= text_field_tag "[bank][account_number]"  %>
      <span class="required">*</span>
      <br />
      <%= label_tag nil, t(:bank_branch) %><br />
      <%= text_field_tag "[bank][bank_branch]" %>
      <%= hidden_field_tag "[bank][status]", :value => "customer" %>
    </div>
  </div>
</fieldset>

app/views/spree/admin/payments/source_views/_banktransfer.html.erb
<fieldset style="width:70%" data-hook="bank_detail">
  <legend ><%= t(:bank_detail) %></legend>
  <% @bank_detail = Spree::BankDetail.find(@payment.source_id) %>
  <table class="index">
    <tr>
      <th colspan="4"><%= t(:bank_details) %></th>
    </tr>
    <tr>
      <td><%= label_tag nil, t(:account_name) %>:</td>
      <td>
        <%= @bank_detail.account_name %>
      <td><%= label_tag nil, t(:account_number) %>:</td>
      <td>
        <%= @bank_detail.account_number %>
      </td>
    </tr>
    <tr>
      <td><%= label_tag nil, t(:bank) %>:</td>
      <td>
        <%= @bank_detail.bank %>
      <td><%= label_tag nil, t(:bank_branch) %>:</td>
      <td>
        <%= @bank_detail.bank_branch %>
      </td>
    </tr>
  </table>
</fieldset>

app/views/spree/checkout/payment/_banktransfer.html.erb
<%#= image_tag 'credit_cards/credit_card.gif', :id => 'credit-card-image' %>
<% param_prefix = "payment_source[#{payment_method.id}]" %>
<%
if @order.payment.present? && @order.payment_method.type == "Spree::PaymentMethod::BankTransfer" && @order.bank_detail.present?
  bank_detail = @order.bank_detail.bank
  acc_number = @order.bank_detail.account_number
  acc_name = @order.bank_detail.account_name
  branch = @order.bank_detail.bank_branch
else
  bank_detail = ""
  acc_number = ""
  acc_name = ""
  branch = ""
end
%>

<div class="field bank" data-hook="bank">
  <%= label_tag nil, t(:bank) %><br />
  <%= select_tag("[bank][bank]", options_from_collection_for_select(Spree::BankDetail.all(:conditions => {:status => "owner"}), :bank, :bank), :selected => bank_detail, :include_blank => true) %>
  <span class="required">*</span>
  <table id="owner_account" class="index"></table>
  <br />
  <%= label_tag nil, t(:account_name) %><br />
  <%= text_field_tag "[bank][account_name]", acc_name  %>
  <span class="required">*</span>
  <br />
  <%= label_tag nil, t(:account_number) %><br />
  <%= text_field_tag "[bank][account_number]", acc_number  %>
  <span class="required">*</span>
  <br />
  <%= label_tag nil, t(:bank_branch) %><br />
  <%= text_field_tag "[bank][bank_branch]" %>
  <%= hidden_field_tag "[bank][status]", :value => "customer" %>
</div>

<script type="text/javascript">
  $("#_bank_bank").change(function(){
    if (this.value != ""){
      $.getJSON("/bank_details/"+this.value+".json",function(data)
      {
        $.each(data, function(i,data)
          {
          var data_html = '<td>'+data.bank+'<br/>'+data.account_name+' - '+data.account_number+'</td>';	
            $("[data-hook=bank] table#owner_account").html(data_html);
          });							
      });
    }
    else{$("[data-hook=bank] table#owner_account").html("");}
    });


  $('input[type="radio"][name="order[payments_attributes][][payment_method_id]"]').click(function() {
    if (this.checked) {
      return ($('#payment_method_' + this.value)).show();
      return ($("[data-hook=bank]")).show();
    }
  });

  $("li").hide();
</script>

app/views/spree/shared/_bank_detail.html.erb
<% unless order.bank_detail.nil? %>
  <span class="bank">
    <%= t(:bank)%> : <%= order.bank_detail.bank %>
  </span>
  <br />
  <span class="account-info">
    <%= t(:account_number)%> : <%= order.bank_detail.account_number %><br/>
    <%= t(:account_name)%> :  <%= order.bank_detail.account_name %>
  </span>
<% end %>